### ISSUE TITLE
Testing using grpc-spring-boot-starter

### ISSUE THREAD

**Issue by horiadruliac** [ST-DDT/grpc-spring-boot-starter#1]
My application must add an entity to the database and restore all elements.

Whilst testing, should I create my own separate client class and use the @GrpcClient annotation to help me 'wire' it in my test class? Should I create the Stub in the testing class? 
What would be the easiest implementation?

In the documentation for testing (https://st-ddt.github.io/grpc-spring-boot-starter/server/testing#unit-tests) it is recommended to just autowire the Service Implementation, but if I annotate my service class implementation with "@GrpcService", IntelliJ writes that it could not autowire (in the test).

--

Which versions do you use?
* Spring (boot): 2.1.6
* grpc-spring-boot-starter: latest
* java: version + architecture (64bit?) 11
* Other relevant libraries...

**Comment by ST-DDT** [comment]
Please report all issues here: https://github.com/yidongnan/grpc-spring-boot-starter
-> https://github.com/yidongnan/grpc-spring-boot-starter/issues/269
